# Generated by Django 6.0.3 on 2026-03-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissaoacesso',
            old_name='data_expiracal',
            new_name='data_expiracao',
        ),
    ]
