# Generated by Django 6.0.3 on 2026-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_data_expiracal_permissaoacesso_data_expiracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='trecho',
            name='fim',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
