# Generated by Django 6.0.3 on 2026-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_trecho_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
